# Generated by Django 5.1.7 on 2025-04-30 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='badania/')),
                ('opis', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
                ('opis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analiza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('zdjecie', models.ImageField(upload_to='analizy/')),
                ('opis', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('badanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analizy', to='core.badanie')),
            ],
        ),
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('data_urodzenia', models.DateField()),
                ('opis', models.TextField(blank=True)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacjenci', to='core.lekarz')),
            ],
        ),
        migrations.AddField(
            model_name='badanie',
            name='pacjent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badania', to='core.pacjent'),
        ),
        migrations.AddField(
            model_name='badanie',
            name='tagi',
            field=models.ManyToManyField(blank=True, related_name='badania', to='core.tag'),
        ),
    ]
