# Generated by Django 5.1.7 on 2025-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badanie',
            name='tagi',
        ),
        migrations.AddField(
            model_name='badanie',
            name='nazwa',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
