# Generated by Django 5.1.7 on 2025-05-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_badanie_tagi_badanie_nazwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='badanie',
            name='tagi',
            field=models.ManyToManyField(blank=True, related_name='badania', to='core.tag'),
        ),
    ]
