# Generated by Django 5.1.7 on 2025-05-05 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_badanie_tagi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badanie',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
